# Parameters for data processing
data_processing:
  test_split_ratio: 0.2
  random_state: 42
  target_column: 'Churn'

# Parameters for model training
training:
  n_estimators: 100
  max_depth: 5
  random_state: 42

# Parameters for feature engineering
features:
  numerical_features:
    - 'tenure'
    - 'MonthlyCharges'
    - 'TotalCharges'
  categorical_features:
    - 'gender'
    - 'Partner'
    - 'Dependents'
    - 'PhoneService'
    - 'MultipleLines'
    - 'InternetService'
    - 'OnlineSecurity'
    - 'OnlineBackup'
    - 'DeviceProtection'
    - 'TechSupport'
    - 'StreamingTV'
    - 'StreamingMovies'
    - 'Contract'
    - 'PaperlessBilling'
    - 'PaymentMethod'

